# Generated by Django 3.2.6 on 2021-09-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210904_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Image', max_length=255, null=True)),
                ('image', models.ImageField(upload_to='media/gallery_images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='videocategory',
            options={'ordering': ('name',), 'verbose_name': 'video category', 'verbose_name_plural': 'Video Categories'},
        ),
    ]
