# Generated by Django 3.2.6 on 2021-09-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210904_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Image category',
                'verbose_name_plural': 'Image Categories',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-pk',), 'verbose_name': 'Image', 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(default='Taggar Associates gallery Image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='Image', max_length=255),
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.imagecategory'),
        ),
    ]
